<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX<channels>
<channels>
<channel>
<name>[COLOR lime]PORTUGAL[/COLOR] [COLOR red] /[/COLOR]  [COLOR yellow]IPTV 1[/COLOR]</name>
<link>http://ignorame</link>
<thumbnail>https://i.imgur.com/wiDXK8M.png</thumbnail>
<fanart>https://i.imgur.com/ofDmewx.png</fanart>
<externallink>UD6IHXEG7C3CWTVOUT46GYVFZD5SGXFNGT3SWXYNJLY2WX4OBT46SW4FZD5SGXFNGL24WXRMELY6CX5NEDZCW4ROJT3SGTZNJ3L2WXNMORYCGWROJ3Z6SXIHTD4IH2BN</externallink>
</channel>
</channels>
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX<channels>
<channels>
<channel>
<name>[COLOR lime]PORTUGAL[/COLOR] [COLOR red] /[/COLOR]  [COLOR yellow]IPTV 2[/COLOR]</name>
<link>http://ignorame</link>
<thumbnail>https://i.imgur.com/wiDXK8M.png</thumbnail>
<fanart>https://i.imgur.com/ofDmewx.png</fanart>
<externallink>UD6IHXIGNB3CWTVOUT46GYVFZD5SGXFNGT3SWXYNJLY2WX4OBT46SW4FZD5SGXFNGL24WXRMELY6CX5NEDZCW4ROJT3SGTZNJ3L2WXNMORYCGWROJ3Z6SXIHTD4IH2BN</externallink>
</channel>
</channels>
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
<channels>
<channel>
<name>[COLOR lime]BRASIL[/COLOR] [COLOR red] /[/COLOR]  [COLOR yellow]IPTV 1[/COLOR]</name>
<link>http://ignorame</link>
<thumbnail>https://i.imgur.com/YteTQ50.png</thumbnail>
<fanart>https://i.imgur.com/ofDmewx.png</fanart>
<externallink>===IH4ROOJM2CWFNTLYEHRVFZD5SGXFNGT3SWXYNJLY2WX4OBT46SW4FZD5SGXFNGL24WXRMELY6CX5NEDZCW4ROJT3SGTZNJ3L2WXNMORYCGWROJ3Z6SXIHTD4IH2BN</externallink>
</channel>
</channels>
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
<channels>
<channel>
<name>[COLOR lime]BRASIL[/COLOR] [COLOR red] /[/COLOR]  [COLOR yellow]IPTV 2[/COLOR]</name>
<link>http://ignorame</link>
<thumbnail>https://i.imgur.com/YteTQ50.png</thumbnail>
<fanart>https://i.imgur.com/ofDmewx.png</fanart>
<externallink>===IH4ROORM2CWFNTLYEHRVFZD5SGXFNGT3SWXYNJLY2WX4OBT46SW4FZD5SGXFNGL24WXRMELY6CX5NEDZCW4ROJT3SGTZNJ3L2WXNMORYCGWROJ3Z6SXIHTD4IH2BN</externallink>
</channel>
</channels>
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX<channels>
<channel>
<name>[COLOR lime]PORTUGAL[/COLOR] [COLOR red] /[/COLOR]  [COLOR yellow]DESPORTO IPTV 1[/COLOR]</name>
<link>http://ignorame</link>
<thumbnail>https://i.imgur.com/E5SUqua.png</thumbnail>
<fanart>https://i.imgur.com/ofDmewx.png</fanart>
<externallink>=A5QH2ZFPD5EXXBOTLZIWWEPUL24WUZMOL26CXFNBL36CR5NMTY6SW4FZD5SGXFNGL24WXRMELY6CX5NEDZCW4ROJT3SGTZNJ3L2WXNMORYCGWROJ3Z6SXIHTD4IH2BN</externallink>
</channel>
</channels>
